version: 2.1
orbs:
    php: circleci/php@1.1.0

jobs:
  build:
    executor: php/default
    steps:
      - checkout:
          method: blobless
      - php/install-php:
          version: '8.1'
      - php/install-composer:
          install-version: '2.4.3'
      - run:
          name: Extra PHP packages
          command: |
            sudo apt-get install -y php8.1-xml php8.1-yaml php8.1-mbstring
      - run:
          name: Composer Install
          command: php8.1 /usr/local/bin/composer install
      - run:
          name: PHPUnit
          command: php8.1 ./vendor/bin/phpunit
      - run:
          name: Execute
          command: php8.1 ./bin/app parseCron "*/10 1,2,3 5-11 1 6 /usr/bin/php --version"
